# Generated by Django 6.0.5 on 2026-05-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_client_id_client_client_type_client_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debtors_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debtors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='debtor_id',
            field=models.CharField(blank=True, help_text='Auto-generated like CRSS/2025/D0001', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='debtor',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtor',
            name='passport_cr_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
