# Generated by Django 6.0.5 on 2026-05-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_debtor_new_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.CharField(blank=True, help_text='Auto-generated like CRSS/2025/01/0001', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
