# Generated by Django 6.0.5 on 2026-05-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('guarantor', 'Guarantor'), ('accounts', 'Accounts'), ('sales_manager', 'Sales Manager'), ('chairman', 'Chairman'), ('assistant_manager', 'Assistant Manager'), ('managing_partner', 'Managing Partner'), ('owner', 'Owner'), ('other', 'Other')], default='other', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.debtor')),
            ],
        ),
    ]
