# Generated by Django 6.0.5 on 2026-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_debtor_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='alias_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('retainer', 'Retainer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='po_box',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('individual', 'Individual'), ('government', 'Government'), ('agency', 'Agency'), ('ngo', 'NGO'), ('other', 'Other')], default='corporate', max_length=20),
        ),
    ]
