# Generated by Django 6.0.5 on 2026-05-25 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_client_extended_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='groups', to='core.case')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_groups_collected', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_groups_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('letter', 'Letter'), ('visit', 'Visit'), ('legal', 'Legal'), ('sms', 'SMS'), ('other', 'Other')], default='call', max_length=20)),
                ('is_legal', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField()),
                ('case_status', models.CharField(choices=[('active', 'Active'), ('broken_promise', 'Broken Promise'), ('contactable', 'Contactable'), ('closed_by_client', 'Closed by Client request'), ('closed', 'Closed')], default='active', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.case')),
                ('followed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
