# Generated by Django 6.0.5 on 2026-05-25 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_followup_casegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(blank=True, max_length=200)),
                ('legal_approved_date', models.DateField(blank=True, null=True)),
                ('legal_status', models.CharField(choices=[('pending', 'Pending'), ('under_execution', 'Under Execution'), ('in_court_hearing', 'In Court Hearing'), ('closed_payment_done', 'Closed-Payment Done'), ('closed', 'Closed'), ('other', 'Other')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_case', to='core.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
