# Generated by Django 6.0.5 on 2026-06-03 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_legalcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('agency', 'Agency'), ('bank', 'Bank'), ('corporate', 'Corporate'), ('education', 'Education'), ('finance', 'Finance'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('individual', 'Individual'), ('insurance', 'Insurance'), ('telecommunication', 'Telecommunication')], default='corporate', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('one_time', 'One time'), ('fixed_regular', 'Fixed Regular'), ('variable_regular', 'Variable Regular')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user_group', models.CharField(choices=[('super_admin', 'Super Admin'), ('collection', 'Collection'), ('lawyer', 'Lawyer'), ('trainee', 'Trainee'), ('management', 'Management'), ('admin', 'Admin')], default='collection', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
