# Generated by Django 6.0.5 on 2026-06-03 12:19

import django.db.models.deletion
from django.db import migrations, models

DEFAULT_GROUPS = [
    'Super Admin', 'Collection', 'Lawyer', 'Trainee',
    'Accounts', 'Management', 'Admin',
]


def create_groups(apps, schema_editor):
    UserGroup = apps.get_model('core', 'UserGroup')
    for name in DEFAULT_GROUPS:
        UserGroup.objects.get_or_create(name=name)


def reverse_groups(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_client_client_type_alter_client_contract_type_and_more'),
    ]

    operations = [
        # 1. Create the UserGroup table
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # 2. Seed default groups
        migrations.RunPython(create_groups, reverse_groups),
        # 3. Make old CharField nullable so we can clear existing values
        migrations.AlterField(
            model_name='userprofile',
            name='user_group',
            field=models.CharField(max_length=30, null=True, blank=True),
        ),
        # 4. Clear old string values (column is now nullable)
        migrations.RunSQL(
            "UPDATE core_userprofile SET user_group = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 5. Switch to FK
        migrations.AlterField(
            model_name='userprofile',
            name='user_group',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='members',
                to='core.usergroup',
            ),
        ),
    ]
