from django.db import migrations

# (state_name, country_name)
STATES = [
    # Oman
    ("Muscat", "Oman"), ("Dhofar", "Oman"), ("Musandam", "Oman"), ("Al Buraimi", "Oman"),
    ("Al Dakhiliyah", "Oman"), ("Al Batinah North", "Oman"), ("Al Batinah South", "Oman"),
    ("Al Sharqiyah North", "Oman"), ("Al Sharqiyah South", "Oman"),
    ("Al Dhahirah", "Oman"), ("Al Wusta", "Oman"),
    # UAE
    ("Abu Dhabi", "United Arab Emirates"), ("Dubai", "United Arab Emirates"),
    ("Sharjah", "United Arab Emirates"), ("Ajman", "United Arab Emirates"),
    ("Umm Al Quwain", "United Arab Emirates"), ("Ras Al Khaimah", "United Arab Emirates"),
    ("Fujairah", "United Arab Emirates"),
    # Saudi Arabia
    ("Riyadh", "Saudi Arabia"), ("Mecca", "Saudi Arabia"), ("Medina", "Saudi Arabia"),
    ("Eastern Province", "Saudi Arabia"), ("Asir", "Saudi Arabia"), ("Tabuk", "Saudi Arabia"),
    ("Hail", "Saudi Arabia"), ("Northern Borders", "Saudi Arabia"), ("Jazan", "Saudi Arabia"),
    ("Najran", "Saudi Arabia"), ("Al Bahah", "Saudi Arabia"), ("Al Jawf", "Saudi Arabia"),
    ("Qassim", "Saudi Arabia"),
    # Kuwait
    ("Al Asimah", "Kuwait"), ("Hawalli", "Kuwait"), ("Farwaniyah", "Kuwait"),
    ("Ahmadi", "Kuwait"), ("Jahra", "Kuwait"), ("Mubarak Al-Kabeer", "Kuwait"),
    # Qatar
    ("Doha", "Qatar"), ("Al Rayyan", "Qatar"), ("Al Wakrah", "Qatar"),
    ("Al Khor", "Qatar"), ("Umm Salal", "Qatar"), ("Al Shamal", "Qatar"),
    # Bahrain
    ("Capital", "Bahrain"), ("Northern", "Bahrain"), ("Southern", "Bahrain"),
    ("Muharraq", "Bahrain"),
    # United Kingdom
    ("Aberdeen City", "United Kingdom"), ("Aberdeenshire", "United Kingdom"),
    ("Angus", "United Kingdom"), ("Bath", "United Kingdom"),
    ("Birmingham", "United Kingdom"), ("Bradford", "United Kingdom"),
    ("Bristol", "United Kingdom"), ("Cambridge", "United Kingdom"),
    ("Cornwall", "United Kingdom"), ("Cumbria", "United Kingdom"),
    ("Devon", "United Kingdom"), ("Dorset", "United Kingdom"),
    ("Durham", "United Kingdom"), ("East Sussex", "United Kingdom"),
    ("Essex", "United Kingdom"), ("Gloucestershire", "United Kingdom"),
    ("Greater London", "United Kingdom"), ("Greater Manchester", "United Kingdom"),
    ("Hampshire", "United Kingdom"), ("Herefordshire", "United Kingdom"),
    ("Hertfordshire", "United Kingdom"), ("Kent", "United Kingdom"),
    ("Lancashire", "United Kingdom"), ("Leicestershire", "United Kingdom"),
    ("Lincolnshire", "United Kingdom"), ("Liverpool", "United Kingdom"),
    ("Norfolk", "United Kingdom"), ("North Yorkshire", "United Kingdom"),
    ("Northumberland", "United Kingdom"), ("Nottinghamshire", "United Kingdom"),
    ("Oxfordshire", "United Kingdom"), ("Somerset", "United Kingdom"),
    ("South Yorkshire", "United Kingdom"), ("Suffolk", "United Kingdom"),
    ("Surrey", "United Kingdom"), ("Tyne and Wear", "United Kingdom"),
    ("Warwickshire", "United Kingdom"), ("West Midlands", "United Kingdom"),
    ("West Sussex", "United Kingdom"), ("West Yorkshire", "United Kingdom"),
    ("Wiltshire", "United Kingdom"), ("Worcestershire", "United Kingdom"),
    # India
    ("Andhra Pradesh", "India"), ("Arunachal Pradesh", "India"), ("Assam", "India"),
    ("Bihar", "India"), ("Chhattisgarh", "India"), ("Goa", "India"),
    ("Gujarat", "India"), ("Haryana", "India"), ("Himachal Pradesh", "India"),
    ("Jharkhand", "India"), ("Karnataka", "India"), ("Kerala", "India"),
    ("Madhya Pradesh", "India"), ("Maharashtra", "India"), ("Manipur", "India"),
    ("Meghalaya", "India"), ("Mizoram", "India"), ("Nagaland", "India"),
    ("Odisha", "India"), ("Punjab", "India"), ("Rajasthan", "India"),
    ("Sikkim", "India"), ("Tamil Nadu", "India"), ("Telangana", "India"),
    ("Tripura", "India"), ("Uttar Pradesh", "India"), ("Uttarakhand", "India"),
    ("West Bengal", "India"), ("Delhi", "India"),
    # Pakistan
    ("Punjab", "Pakistan"), ("Sindh", "Pakistan"), ("Khyber Pakhtunkhwa", "Pakistan"),
    ("Balochistan", "Pakistan"), ("Islamabad", "Pakistan"), ("Gilgit-Baltistan", "Pakistan"),
    # United States
    ("Alabama", "United States"), ("Alaska", "United States"), ("Arizona", "United States"),
    ("Arkansas", "United States"), ("California", "United States"), ("Colorado", "United States"),
    ("Connecticut", "United States"), ("Delaware", "United States"), ("Florida", "United States"),
    ("Georgia", "United States"), ("Hawaii", "United States"), ("Idaho", "United States"),
    ("Illinois", "United States"), ("Indiana", "United States"), ("Iowa", "United States"),
    ("Kansas", "United States"), ("Kentucky", "United States"), ("Louisiana", "United States"),
    ("Maine", "United States"), ("Maryland", "United States"), ("Massachusetts", "United States"),
    ("Michigan", "United States"), ("Minnesota", "United States"), ("Mississippi", "United States"),
    ("Missouri", "United States"), ("Montana", "United States"), ("Nebraska", "United States"),
    ("Nevada", "United States"), ("New Hampshire", "United States"), ("New Jersey", "United States"),
    ("New Mexico", "United States"), ("New York", "United States"), ("North Carolina", "United States"),
    ("North Dakota", "United States"), ("Ohio", "United States"), ("Oklahoma", "United States"),
    ("Oregon", "United States"), ("Pennsylvania", "United States"), ("Rhode Island", "United States"),
    ("South Carolina", "United States"), ("South Dakota", "United States"),
    ("Tennessee", "United States"), ("Texas", "United States"), ("Utah", "United States"),
    ("Vermont", "United States"), ("Virginia", "United States"), ("Washington", "United States"),
    ("West Virginia", "United States"), ("Wisconsin", "United States"), ("Wyoming", "United States"),
    # Australia
    ("New South Wales", "Australia"), ("Victoria", "Australia"), ("Queensland", "Australia"),
    ("Western Australia", "Australia"), ("South Australia", "Australia"),
    ("Tasmania", "Australia"), ("Northern Territory", "Australia"),
    ("Australian Capital Territory", "Australia"),
    # Germany
    ("Baden-Württemberg", "Germany"), ("Bavaria", "Germany"), ("Berlin", "Germany"),
    ("Brandenburg", "Germany"), ("Bremen", "Germany"), ("Hamburg", "Germany"),
    ("Hesse", "Germany"), ("Lower Saxony", "Germany"), ("Mecklenburg-Vorpommern", "Germany"),
    ("North Rhine-Westphalia", "Germany"), ("Rhineland-Palatinate", "Germany"),
    ("Saarland", "Germany"), ("Saxony", "Germany"), ("Saxony-Anhalt", "Germany"),
    ("Schleswig-Holstein", "Germany"), ("Thuringia", "Germany"),
    # France
    ("Auvergne-Rhône-Alpes", "France"), ("Bourgogne-Franche-Comté", "France"),
    ("Brittany", "France"), ("Centre-Val de Loire", "France"), ("Corsica", "France"),
    ("Grand Est", "France"), ("Hauts-de-France", "France"), ("Île-de-France", "France"),
    ("Normandy", "France"), ("Nouvelle-Aquitaine", "France"), ("Occitanie", "France"),
    ("Pays de la Loire", "France"), ("Provence-Alpes-Côte d'Azur", "France"),
    # Canada
    ("Alberta", "Canada"), ("British Columbia", "Canada"), ("Manitoba", "Canada"),
    ("New Brunswick", "Canada"), ("Newfoundland and Labrador", "Canada"),
    ("Northwest Territories", "Canada"), ("Nova Scotia", "Canada"), ("Nunavut", "Canada"),
    ("Ontario", "Canada"), ("Prince Edward Island", "Canada"), ("Quebec", "Canada"),
    ("Saskatchewan", "Canada"), ("Yukon", "Canada"),
    # Nigeria
    ("Abia", "Nigeria"), ("Adamawa", "Nigeria"), ("Akwa Ibom", "Nigeria"),
    ("Anambra", "Nigeria"), ("Bauchi", "Nigeria"), ("Bayelsa", "Nigeria"),
    ("Benue", "Nigeria"), ("Borno", "Nigeria"), ("Cross River", "Nigeria"),
    ("Delta", "Nigeria"), ("Ebonyi", "Nigeria"), ("Edo", "Nigeria"),
    ("Ekiti", "Nigeria"), ("Enugu", "Nigeria"), ("Gombe", "Nigeria"),
    ("Imo", "Nigeria"), ("Jigawa", "Nigeria"), ("Kaduna", "Nigeria"),
    ("Kano", "Nigeria"), ("Katsina", "Nigeria"), ("Kebbi", "Nigeria"),
    ("Kogi", "Nigeria"), ("Kwara", "Nigeria"), ("Lagos", "Nigeria"),
    ("Nasarawa", "Nigeria"), ("Niger", "Nigeria"), ("Ogun", "Nigeria"),
    ("Ondo", "Nigeria"), ("Osun", "Nigeria"), ("Oyo", "Nigeria"),
    ("Plateau", "Nigeria"), ("Rivers", "Nigeria"), ("Sokoto", "Nigeria"),
    ("Taraba", "Nigeria"), ("Yobe", "Nigeria"), ("Zamfara", "Nigeria"),
    ("FCT Abuja", "Nigeria"),
    # Egypt
    ("Cairo", "Egypt"), ("Alexandria", "Egypt"), ("Aswan", "Egypt"),
    ("Asyut", "Egypt"), ("Beheira", "Egypt"), ("Beni Suef", "Egypt"),
    ("Dakahlia", "Egypt"), ("Damietta", "Egypt"), ("Faiyum", "Egypt"),
    ("Gharbia", "Egypt"), ("Giza", "Egypt"), ("Ismailia", "Egypt"),
    ("Kafr El Sheikh", "Egypt"), ("Luxor", "Egypt"), ("Matruh", "Egypt"),
    ("Minya", "Egypt"), ("Monufia", "Egypt"), ("New Valley", "Egypt"),
    ("North Sinai", "Egypt"), ("Port Said", "Egypt"), ("Qalyubia", "Egypt"),
    ("Qena", "Egypt"), ("Red Sea", "Egypt"), ("Sharqia", "Egypt"),
    ("Sohag", "Egypt"), ("South Sinai", "Egypt"), ("Suez", "Egypt"),
    # Philippines
    ("Abra", "Philippines"), ("Agusan del Norte", "Philippines"),
    ("Agusan del Sur", "Philippines"), ("Aklan", "Philippines"),
    ("Albay", "Philippines"), ("Antique", "Philippines"),
    ("Apayao", "Philippines"), ("Aurora", "Philippines"),
    ("Basilan", "Philippines"), ("Bataan", "Philippines"),
    ("Batanes", "Philippines"), ("Batangas", "Philippines"),
    ("Benguet", "Philippines"), ("Biliran", "Philippines"),
    ("Bohol", "Philippines"), ("Bukidnon", "Philippines"),
    ("Bulacan", "Philippines"), ("Cagayan", "Philippines"),
    ("Camarines Norte", "Philippines"), ("Camarines Sur", "Philippines"),
    ("Camiguin", "Philippines"), ("Capiz", "Philippines"),
    ("Catanduanes", "Philippines"), ("Cavite", "Philippines"),
    ("Cebu", "Philippines"), ("Davao de Oro", "Philippines"),
    ("Davao del Norte", "Philippines"), ("Davao del Sur", "Philippines"),
    ("Davao Occidental", "Philippines"), ("Davao Oriental", "Philippines"),
    ("Dinagat Islands", "Philippines"), ("Eastern Samar", "Philippines"),
    ("Guimaras", "Philippines"), ("Ifugao", "Philippines"),
    ("Ilocos Norte", "Philippines"), ("Ilocos Sur", "Philippines"),
    ("Iloilo", "Philippines"), ("Isabela", "Philippines"),
    ("Kalinga", "Philippines"), ("La Union", "Philippines"),
    ("Laguna", "Philippines"), ("Lanao del Norte", "Philippines"),
    ("Lanao del Sur", "Philippines"), ("Leyte", "Philippines"),
    ("Maguindanao", "Philippines"), ("Marinduque", "Philippines"),
    ("Masbate", "Philippines"), ("Metro Manila", "Philippines"),
    ("Misamis Occidental", "Philippines"), ("Misamis Oriental", "Philippines"),
    ("Mountain Province", "Philippines"), ("Negros Occidental", "Philippines"),
    ("Negros Oriental", "Philippines"), ("Northern Samar", "Philippines"),
    ("Nueva Ecija", "Philippines"), ("Nueva Vizcaya", "Philippines"),
    ("Occidental Mindoro", "Philippines"), ("Oriental Mindoro", "Philippines"),
    ("Palawan", "Philippines"), ("Pampanga", "Philippines"),
    ("Pangasinan", "Philippines"), ("Quezon", "Philippines"),
    ("Quirino", "Philippines"), ("Rizal", "Philippines"),
    ("Romblon", "Philippines"), ("Samar", "Philippines"),
    ("Sarangani", "Philippines"), ("Siquijor", "Philippines"),
    ("Sorsogon", "Philippines"), ("South Cotabato", "Philippines"),
    ("Southern Leyte", "Philippines"), ("Sultan Kudarat", "Philippines"),
    ("Sulu", "Philippines"), ("Surigao del Norte", "Philippines"),
    ("Surigao del Sur", "Philippines"), ("Tarlac", "Philippines"),
    ("Tawi-Tawi", "Philippines"), ("Zambales", "Philippines"),
    ("Zamboanga del Norte", "Philippines"), ("Zamboanga del Sur", "Philippines"),
    ("Zamboanga Sibugay", "Philippines"),
    # Italy
    ("Abruzzo", "Italy"), ("Aosta Valley", "Italy"), ("Apulia", "Italy"),
    ("Basilicata", "Italy"), ("Calabria", "Italy"), ("Campania", "Italy"),
    ("Emilia-Romagna", "Italy"), ("Friuli-Venezia Giulia", "Italy"),
    ("Lazio", "Italy"), ("Liguria", "Italy"), ("Lombardy", "Italy"),
    ("Marche", "Italy"), ("Molise", "Italy"), ("Piedmont", "Italy"),
    ("Sardinia", "Italy"), ("Sicily", "Italy"), ("Trentino-South Tyrol", "Italy"),
    ("Tuscany", "Italy"), ("Umbria", "Italy"), ("Veneto", "Italy"),
    # Azerbaijan
    ("Abseron", "Azerbaijan"), ("Agcabadi", "Azerbaijan"), ("Agdam", "Azerbaijan"),
    ("Agdas", "Azerbaijan"), ("Agstafa", "Azerbaijan"), ("Agsu", "Azerbaijan"),
    ("Astara", "Azerbaijan"), ("Baku", "Azerbaijan"), ("Balakan", "Azerbaijan"),
    ("Barda", "Azerbaijan"), ("Beylagan", "Azerbaijan"), ("Bilasuvar", "Azerbaijan"),
    ("Ganja", "Azerbaijan"), ("Goranboy", "Azerbaijan"), ("Goychay", "Azerbaijan"),
    ("Goygol", "Azerbaijan"), ("Hajigabul", "Azerbaijan"), ("Imishli", "Azerbaijan"),
    ("Ismayilli", "Azerbaijan"), ("Jabrayil", "Azerbaijan"), ("Jalilabad", "Azerbaijan"),
    ("Kalbajar", "Azerbaijan"), ("Kurdamir", "Azerbaijan"), ("Lachin", "Azerbaijan"),
    ("Lankaran", "Azerbaijan"), ("Lerik", "Azerbaijan"), ("Masally", "Azerbaijan"),
    ("Mingachevir", "Azerbaijan"), ("Nakhchivan", "Azerbaijan"), ("Neftchala", "Azerbaijan"),
    ("Oghuz", "Azerbaijan"), ("Qabala", "Azerbaijan"), ("Qakh", "Azerbaijan"),
    ("Qazakh", "Azerbaijan"), ("Quba", "Azerbaijan"), ("Qubadli", "Azerbaijan"),
    ("Qusar", "Azerbaijan"), ("Saatly", "Azerbaijan"), ("Sabirabad", "Azerbaijan"),
    ("Salyan", "Azerbaijan"), ("Shamakhi", "Azerbaijan"), ("Shaki", "Azerbaijan"),
    ("Shamkir", "Azerbaijan"), ("Shirvan", "Azerbaijan"), ("Shusha", "Azerbaijan"),
    ("Siyazan", "Azerbaijan"), ("Sumgait", "Azerbaijan"), ("Tartar", "Azerbaijan"),
    ("Tovuz", "Azerbaijan"), ("Ujar", "Azerbaijan"), ("Khachmaz", "Azerbaijan"),
    ("Khizi", "Azerbaijan"), ("Xankandi", "Azerbaijan"), ("Yardimli", "Azerbaijan"),
    ("Yevlakh", "Azerbaijan"), ("Zangilan", "Azerbaijan"), ("Zaqatala", "Azerbaijan"),
    ("Zardab", "Azerbaijan"),
    # Georgia (country)
    ("Abashis Raioni", "Georgia"), ("Abkhazia", "Georgia"), ("Adjara", "Georgia"),
    ("Akhalkalaki", "Georgia"), ("Akhaltsikhe", "Georgia"), ("Bolnisi", "Georgia"),
    ("Borjomi", "Georgia"), ("Gori", "Georgia"), ("Gurjaani", "Georgia"),
    ("Imereti", "Georgia"), ("Kakheti", "Georgia"), ("Kvemo Kartli", "Georgia"),
    ("Mtskheta-Mtianeti", "Georgia"), ("Racha-Lechkhumi", "Georgia"),
    ("Samegrelo-Zemo Svaneti", "Georgia"), ("Samtskhe-Javakheti", "Georgia"),
    ("Shida Kartli", "Georgia"), ("Tbilisi", "Georgia"),
    # Switzerland
    ("Aargau", "Switzerland"), ("Appenzell Ausserrhoden", "Switzerland"),
    ("Appenzell Innerrhoden", "Switzerland"), ("Basel-Landschaft", "Switzerland"),
    ("Basel-Stadt", "Switzerland"), ("Bern", "Switzerland"),
    ("Fribourg", "Switzerland"), ("Geneva", "Switzerland"),
    ("Glarus", "Switzerland"), ("Graubünden", "Switzerland"),
    ("Jura", "Switzerland"), ("Lucerne", "Switzerland"),
    ("Neuchâtel", "Switzerland"), ("Nidwalden", "Switzerland"),
    ("Obwalden", "Switzerland"), ("Schaffhausen", "Switzerland"),
    ("Schwyz", "Switzerland"), ("Solothurn", "Switzerland"),
    ("St. Gallen", "Switzerland"), ("Thurgau", "Switzerland"),
    ("Ticino", "Switzerland"), ("Uri", "Switzerland"),
    ("Valais", "Switzerland"), ("Vaud", "Switzerland"),
    ("Zug", "Switzerland"), ("Zurich", "Switzerland"),
    # Indonesia
    ("Aceh", "Indonesia"), ("Bali", "Indonesia"), ("Bangka Belitung", "Indonesia"),
    ("Banten", "Indonesia"), ("Bengkulu", "Indonesia"), ("Central Java", "Indonesia"),
    ("Central Kalimantan", "Indonesia"), ("Central Sulawesi", "Indonesia"),
    ("East Java", "Indonesia"), ("East Kalimantan", "Indonesia"),
    ("East Nusa Tenggara", "Indonesia"), ("Gorontalo", "Indonesia"),
    ("Jakarta", "Indonesia"), ("Jambi", "Indonesia"), ("Lampung", "Indonesia"),
    ("Maluku", "Indonesia"), ("North Kalimantan", "Indonesia"),
    ("North Maluku", "Indonesia"), ("North Sulawesi", "Indonesia"),
    ("North Sumatra", "Indonesia"), ("Papua", "Indonesia"),
    ("Riau", "Indonesia"), ("Riau Islands", "Indonesia"),
    ("South Kalimantan", "Indonesia"), ("South Sulawesi", "Indonesia"),
    ("South Sumatra", "Indonesia"), ("Southeast Sulawesi", "Indonesia"),
    ("West Java", "Indonesia"), ("West Kalimantan", "Indonesia"),
    ("West Nusa Tenggara", "Indonesia"), ("West Papua", "Indonesia"),
    ("West Sulawesi", "Indonesia"), ("West Sumatra", "Indonesia"),
    ("Yogyakarta", "Indonesia"),
    # Yemen
    ("Abyan", "Yemen"), ("Aden", "Yemen"), ("Al Bayda", "Yemen"),
    ("Al Hudaydah", "Yemen"), ("Al Jawf", "Yemen"), ("Al Mahrah", "Yemen"),
    ("Al Mahwit", "Yemen"), ("Amran", "Yemen"), ("Dhamar", "Yemen"),
    ("Hadramawt", "Yemen"), ("Hajjah", "Yemen"), ("Ibb", "Yemen"),
    ("Lahij", "Yemen"), ("Marib", "Yemen"), ("Raymah", "Yemen"),
    ("Saada", "Yemen"), ("Sanaa", "Yemen"), ("Shabwah", "Yemen"),
    ("Socotra", "Yemen"), ("Taiz", "Yemen"),
    # Bahamas
    ("Acklins and Crooked Islands", "Bahamas"), ("Berry Islands", "Bahamas"),
    ("Bimini", "Bahamas"), ("Black Point", "Bahamas"), ("Cat Island", "Bahamas"),
    ("Central Abaco", "Bahamas"), ("Central Andros", "Bahamas"),
    ("Central Eleuthera", "Bahamas"), ("City of Freeport", "Bahamas"),
    ("Crooked Island", "Bahamas"), ("East Grand Bahama", "Bahamas"),
    ("Exuma", "Bahamas"), ("Grand Cay", "Bahamas"), ("Harbour Island", "Bahamas"),
    ("Hope Town", "Bahamas"), ("Inagua", "Bahamas"), ("Long Island", "Bahamas"),
    ("Mangrove Cay", "Bahamas"), ("Mayaguana", "Bahamas"), ("Moore's Island", "Bahamas"),
    ("New Providence", "Bahamas"), ("North Abaco", "Bahamas"),
    ("North Andros", "Bahamas"), ("North Eleuthera", "Bahamas"),
    ("Rum Cay", "Bahamas"), ("San Salvador", "Bahamas"),
    ("South Abaco", "Bahamas"), ("South Andros", "Bahamas"),
    ("South Eleuthera", "Bahamas"), ("Spanish Wells", "Bahamas"),
    ("West Grand Bahama", "Bahamas"),
]


def seed_states(apps, schema_editor):
    Country = apps.get_model('core', 'Country')
    State = apps.get_model('core', 'State')

    country_cache = {c.name: c for c in Country.objects.all()}
    for state_name, country_name in STATES:
        country = country_cache.get(country_name)
        if country:
            State.objects.get_or_create(name=state_name, country=country)


def unseed_states(apps, schema_editor):
    apps.get_model('core', 'State').objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [('core', '0015_state')]
    operations = [migrations.RunPython(seed_states, unseed_states)]
