# Generated by Django 6.0.5 on 2026-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('symbol_left', models.CharField(blank=True, max_length=10)),
                ('symbol_right', models.CharField(blank=True, max_length=10)),
                ('value', models.DecimalField(decimal_places=5, default=1, max_digits=14)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
