# Generated by Django 6.0.5 on 2026-06-04 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLoginAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('visible_date_from', models.DateField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_accesses', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
