# Generated by Django 6.0.5 on 2026-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_reminder_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='cr_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtor',
            name='occi_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='debtor',
            name='vatin_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
