# Generated by Django 6.0.5 on 2026-06-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_org_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debtor_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['debtor_type', 'order', 'name'],
                'unique_together': {('name', 'debtor_type')},
            },
        ),
    ]
