# Generated by Django 6.0.5 on 2026-06-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_seed_debtor_status_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorRelatedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation_type', models.CharField(choices=[('parent', 'Parent Company'), ('sister', 'Sister Company'), ('subsidiary', 'Subsidiary'), ('other', 'Other')], default='sister', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='core.debtor')),
            ],
            options={
                'ordering': ['relation_type', 'name'],
            },
        ),
    ]
