# Generated by Django 6.0.5 on 2026-06-13 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_case_detail_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='core_case_created_333c39_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='core_case_status_59308c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='core_case_client__02885f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['debtor'], name='core_case_debtor__490edc_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['collector'], name='core_case_collect_a6c468_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='core_client_created_cf382f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='core_client_name_76d9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='core_client_status_d6704e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='core_client_client__6790f9_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['-created_at'], name='core_debtor_created_06ca04_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['name'], name='core_debtor_name_440f37_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['status'], name='core_debtor_status_36eee8_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['debtor_id'], name='core_debtor_debtor__913ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['email'], name='core_debtor_email_753ffa_idx'),
        ),
    ]
