# Generated by Django 6.0.5 on 2026-06-13 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='additional_users',
            field=models.ManyToManyField(blank=True, related_name='additional_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
