# Generated by Django 6.0.5 on 2026-06-15 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename_crss_to_twz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(blank=True, help_text='Auto-generated like TWZ/2025/01/0001', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, help_text='Auto-generated like TWZ/2025/01/C001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_id',
            field=models.CharField(blank=True, help_text='Auto-generated like TWZ/2025/D0001', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
