# Generated by Django 6.0.5 on 2026-06-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_case_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collection_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_payments', to='core.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.paymentmode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='core.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
