# Generated by Django 6.0.5 on 2026-06-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_payment_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='commission',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='case',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.currency'),
        ),
        migrations.AddField(
            model_name='case',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='case',
            name='discount_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='principal_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
