# Generated by Django 6.0.5 on 2026-06-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_case_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseattachment',
            name='attachment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_attachments', to='core.attachmenttype'),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
