# Generated by Django 6.0.5 on 2026-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_rename_compass_payment_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False),
        ),
    ]
