# Generated by Django 6.0.5 on 2026-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_payment_is_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other'), ('direct', 'Direct'), ('check', 'Check'), ('promise', 'Promise')], default='bank_transfer', max_length=20),
        ),
    ]
