# Generated by Django 6.0.5 on 2026-06-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_clientloginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_status', models.BooleanField(default=False)),
                ('can_financial', models.BooleanField(default=False)),
                ('can_collector', models.BooleanField(default=False)),
                ('can_followup', models.BooleanField(default=False)),
                ('can_history', models.BooleanField(default=False)),
                ('can_payment_history', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_accesses', to='core.clientloginaccess')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='core.case')),
            ],
            options={
                'unique_together': {('access', 'case')},
            },
        ),
    ]
