# Generated by Django 6.0.5 on 2026-06-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_clientcaseaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='core.clientloginaccess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
