# Generated by Django 6.0.5 on 2026-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_clientloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcaseaccess',
            name='can_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
