# Generated by Django 6.0.5 on 2026-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_clientcaseaccess_can_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloginaccess',
            name='expires_on',
            field=models.DateField(blank=True, help_text='Access auto-disables after this date. Blank = never.', null=True),
        ),
    ]
