# Generated by Django 6.0.5 on 2026-06-27 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_clientloginaccess_expires_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('logout_type', models.CharField(blank=True, choices=[('manual', 'Manual logout'), ('auto_idle', 'Auto logout (idle)'), ('relogin', 'Closed on new login')], max_length=20, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', 'login_at'], name='core_attend_user_id_7f92fe_idx')],
            },
        ),
    ]
