# Generated by Django 6.0.5 on 2026-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_attendancesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('broken_promise', 'Broken Promise'), ('contactable', 'Contactable'), ('legal_action_approved', 'Legal Action Approved'), ('closed_by_client', 'Closed by Client request'), ('closed', 'Closed')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='followup',
            name='case_status',
            field=models.CharField(choices=[('active', 'Active'), ('broken_promise', 'Broken Promise'), ('contactable', 'Contactable'), ('legal_action_approved', 'Legal Action Approved'), ('closed_by_client', 'Closed by Client request'), ('closed', 'Closed')], default='active', max_length=30),
        ),
    ]
