# Generated by Django 6.0.5 on 2026-06-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_case_status_alter_followup_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='legal_status',
            field=models.CharField(default='New Legal Case', max_length=100),
        ),
        migrations.CreateModel(
            name='LegalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_fees_created', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='core.legalfeetype')),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.legalcase')),
            ],
            options={
                'ordering': ['-fee_date', '-created_at'],
            },
        ),
    ]
