# Generated by Django 6.0.5 on 2026-06-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_legalcase_legal_status_legalfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.agency'),
        ),
    ]
