# Generated by Django 6.0.5 on 2026-06-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_case_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='judgement_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='judgment_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_cases', to='core.lawyer'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='lawyer_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='legal_advisor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='legal_case_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='legal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='next_hearing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
