# Generated by Django 6.0.5 on 2026-07-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_chatmessage_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
