# Generated by Django 6.0.5 on 2026-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_chatmessage_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='google_location',
            field=models.CharField(blank=True, help_text='Google Maps link or location', max_length=500),
        ),
    ]
