# Generated by Django 6.0.5 on 2026-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_client_google_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorcontact',
            name='phone',
            field=models.CharField(blank=True, help_text='Multiple numbers may be comma-separated.', max_length=255),
        ),
    ]
