# Generated by Django 6.0.5 on 2026-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_debtorcontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_ips',
            field=models.CharField(blank=True, help_text='Comma-separated IP addresses this user may log in from. Leave blank to allow any IP.', max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('payment', 'Payment'), ('view', 'View'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
