# Generated by Django 6.0.5 on 2026-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_userprofile_allowed_ips_alter_activitylog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='employer_phone',
            field=models.CharField(blank=True, help_text='Multiple numbers may be comma-separated.', max_length=255),
        ),
    ]
