# Generated by Django 6.0.5 on 2026-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_debtor_employer_phone_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorcontact',
            name='contact_type',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('assistant_manager', 'Assistant Manager'), ('ceo', 'CEO'), ('chairman', 'Chairman'), ('colleague', 'Colleague'), ('daughter', 'Daughter'), ('father', 'Father'), ('friend', 'Friend'), ('guarantor', 'Guarantor'), ('guardian', 'Guardian'), ('managing_partner', 'Managing Partner'), ('mother', 'Mother'), ('other', 'Other'), ('owner', 'Owner'), ('sales_manager', 'Sales Manager'), ('sibling', 'Sibling'), ('son', 'Son'), ('spouse', 'Spouse')], default='other', max_length=30),
        ),
    ]
