# Generated by Django 6.0.5 on 2026-07-18 05:31

from django.db import migrations, models
from django.db.models import F


def backfill_outstanding(apps, schema_editor):
    # Reconstruct the original outstanding for existing cases: the Add Case
    # wizard computes Total Approved = Outstanding − Discount, so the inverse
    # holds for data created before this field existed.
    Case = apps.get_model('core', 'Case')
    Case.objects.filter(outstanding_amount=0).update(
        outstanding_amount=F('approved_amount') + F('discount_amount')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_debtorcontact_relationship_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_outstanding, migrations.RunPython.noop),
    ]
