# Generated by Django 6.0.5 on 2026-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_case_outstanding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='discount_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
