# Generated by Django 6.0.5 on 2026-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_case_discount_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('letter', 'Letter'), ('visit', 'Visit'), ('legal', 'Legal'), ('sms', 'SMS'), ('other', 'Other')], default='call', max_length=100),
        ),
    ]
