# Generated by Django 6.0.5 on 2026-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_followup_follow_up_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='promise_to_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('broken_promise', 'Broken Promise'), ('contactable', 'Contactable'), ('promise_to_pay', 'Promise to Pay'), ('legal_action_approved', 'Legal Action Approved'), ('closed_by_client', 'Closed by Client request'), ('closed', 'Closed')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='followup',
            name='case_status',
            field=models.CharField(choices=[('active', 'Active'), ('broken_promise', 'Broken Promise'), ('contactable', 'Contactable'), ('promise_to_pay', 'Promise to Pay'), ('legal_action_approved', 'Legal Action Approved'), ('closed_by_client', 'Closed by Client request'), ('closed', 'Closed')], default='active', max_length=30),
        ),
    ]
