# Generated by Django 6.0.5 on 2026-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_case_promise_to_pay_date_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Approved'), ('bounced', 'Rejected')], default='pending', max_length=20),
        ),
    ]
