# Generated by Django 6.0.5 on 2026-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_reminder_completed_at_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='promise_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
