# Generated by Django 6.0.5 on 2026-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_case_promise_completed_at_payment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_grants',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_revokes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
