# Generated by Django 6.0.5 on 2026-07-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_seed_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
