# Generated by Django 6.0.5 on 2026-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_userprofile_address_userprofile_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtorcontact',
            name='contact_type',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('assistant_manager', 'Assistant Manager'), ('ceo', 'CEO'), ('chairman', 'Chairman'), ('colleague', 'Colleague'), ('daughter', 'Daughter'), ('father', 'Father'), ('friend', 'Friend'), ('guarantor', 'Guarantor'), ('guardian', 'Guardian'), ('managing_partner', 'Managing Partner'), ('mother', 'Mother'), ('other', 'Other'), ('owner', 'Owner'), ('sales_manager', 'Sales Manager'), ('self', 'Self'), ('sibling', 'Sibling'), ('son', 'Son'), ('spouse', 'Spouse')], default='other', max_length=30),
        ),
    ]
