# Generated by Django 6.0.5 on 2026-09-12 07:50

from django.db import migrations, models


def reassign_admin_to_client(apps, schema_editor):
    """'Admin' is being dropped as a Contact Type. Existing rows move to
    'Client' — except where a (name, client) row already exists, in which
    case the admin-typed duplicate is just dropped (name+type is unique)."""
    ContactType = apps.get_model('core', 'ContactType')
    for row in ContactType.objects.filter(type='admin'):
        if ContactType.objects.filter(name__iexact=row.name, type='client').exclude(pk=row.pk).exists():
            row.delete()
        else:
            row.type = 'client'
            row.save(update_fields=['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_enable_regional_currencies_only'),
    ]

    operations = [
        migrations.RunPython(reassign_admin_to_client, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contacttype',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('debtor', 'Debtor')], default='client', max_length=10),
        ),
    ]
