# Generated by Django 6.0.5 on 2026-09-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_remove_admin_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmenttype',
            name='type',
            field=models.CharField(default='case', max_length=30),
        ),
    ]
