"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for any real deployment — this
# fallback is an obviously-insecure placeholder for local dev only.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-CHANGE-ME-for-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.idle_settings',
                'core.context_processors.converter_currencies',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Muscat'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ---------------------------------------------------------------------------
# Attendance / idle auto-logout.
# IDLE_LOGOUT_MINUTES  — minutes of no mouse/keyboard/scroll activity before the
#                        dashboard automatically logs the staff member out.
# IDLE_WARNING_SECONDS — how long before that the "you're about to be logged
#                        out" countdown popup appears (with a Stay logged in
#                        button). Surfaced to the browser via the
#                        core.context_processors.idle_settings processor and the
#                        attendance heartbeat endpoint.
# ---------------------------------------------------------------------------
import os as _idle_os
IDLE_LOGOUT_MINUTES = int(_idle_os.environ.get('IDLE_LOGOUT_MINUTES', '20'))
IDLE_WARNING_SECONDS = int(_idle_os.environ.get('IDLE_WARNING_SECONDS', '60'))

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
    'https://*.trycloudflare.com',
    'https://*.loca.lt',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Trust ngrok's forwarded HTTPS headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Cookie security.
# Over a plain http://127.0.0.1 connection the browser DROPS any cookie marked
# Secure, which means the CSRF cookie never gets stored and every POST (login,
# OTP request, etc.) fails. So default to relaxed cookies for local dev, and
# only enforce Secure + SameSite=None when serving over HTTPS (e.g. ngrok).
# Turn the strict mode on with:  export COOKIE_SECURE=1
import os as _os
_secure_cookies = _os.environ.get('COOKIE_SECURE', '0') == '1'

CSRF_COOKIE_SECURE      = _secure_cookies
SESSION_COOKIE_SECURE   = _secure_cookies
CSRF_COOKIE_SAMESITE    = 'None' if _secure_cookies else 'Lax'
SESSION_COOKIE_SAMESITE = 'None' if _secure_cookies else 'Lax'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Email (used for the client OTP login). Fill these in with your real SMTP
# credentials. They are read from environment variables so you don't have to
# hard-code secrets — e.g. for Gmail:
#   export EMAIL_HOST_USER="you@gmail.com"
#   export EMAIL_HOST_PASSWORD="your-16-char-app-password"
# If no credentials are provided, OTP emails are printed to the runserver
# console instead (handy for local testing without an SMTP server).
# ---------------------------------------------------------------------------
import os

# OTP emails are sent FROM this address (info@tawazonoman.com) to the client's
# registered email. The SMTP login user defaults to the same mailbox.
# Zoho Mail SMTP. If your Zoho account is on a regional data center, change the
# host to match: smtp.zoho.eu / smtp.zoho.in / smtp.zoho.com.au, etc. Business
# (paid) accounts can also use smtppro.zoho.com.
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.zoho.in')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_USE_SSL       = os.environ.get('EMAIL_USE_SSL', '0') == '1'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', 'info@tawazonoman.com')
# SECURITY: no default here — set EMAIL_HOST_PASSWORD in the environment.
# Prefer a Zoho app-specific password over the account password.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Tawazon Collection <info@tawazonoman.com>',
)

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # No SMTP credentials configured — print the email (and OTP) to the console.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# How long an OTP code stays valid, in minutes.
CLIENT_OTP_TTL_MINUTES = int(os.environ.get('CLIENT_OTP_TTL_MINUTES', '10'))
