"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for any real deployment — this
# fallback is an obviously-insecure placeholder for local dev only.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-CHANGE-ME-for-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True to match local dev as it's always been. On a real deploy,
# set:  export DJANGO_DEBUG=0
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# Comma-separated list of allowed hostnames, e.g.:
#   export DJANGO_ALLOWED_HOSTS="app.tawazonoman.com,www.tawazonoman.com"
# Defaults to '*' so nothing already running breaks — narrow this on a real
# deploy so the app only answers to your real domain.
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] or ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves static files directly from the app process — no separate static
    # file host/CDN needed to get a working production deploy.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.idle_settings',
                'core.context_processors.converter_currencies',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Set DATABASE_URL to point at a real Postgres instance, e.g.:
#   export DATABASE_URL="postgres://user:password@host:5432/dbname"
# Falls back to the local SQLite file when it's not set (local dev only —
# SQLite is not safe for concurrent multi-user production use).
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# ---------------------------------------------------------------------------
# Cache.
#
# Set REDIS_URL to a running Redis instance for a real shared cache, e.g.:
#   export REDIS_URL="redis://127.0.0.1:6379/1"
# Used to cache the expensive dashboard summary view and to hold sessions, so
# heavy staff pages and client-portal traffic don't keep re-hitting the DB.
# With no REDIS_URL set it falls back to a per-process in-memory cache, which
# is fine for local dev / a single worker but not shared between workers.
# ---------------------------------------------------------------------------
_redis_url = os.environ.get('REDIS_URL', '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
    # Read sessions from cache, write through to the DB so they survive a
    # Redis restart. Keeps a DB round-trip off the hot path for every request.
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'tawazon-locmem',
        }
    }

# How long (seconds) the cached dashboard summary stays fresh. Staff won't
# notice a slightly stale total; this removes the dashboard as a load source.
DASHBOARD_CACHE_SECONDS = int(os.environ.get('DASHBOARD_CACHE_SECONDS', '90'))


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Muscat'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ---------------------------------------------------------------------------
# Attendance / idle auto-logout.
# IDLE_LOGOUT_MINUTES  — minutes of no mouse/keyboard/scroll activity before the
#                        dashboard automatically logs the staff member out.
# IDLE_WARNING_SECONDS — how long before that the "you're about to be logged
#                        out" countdown popup appears (with a Stay logged in
#                        button). Surfaced to the browser via the
#                        core.context_processors.idle_settings processor and the
#                        attendance heartbeat endpoint.
# ---------------------------------------------------------------------------
import os as _idle_os
IDLE_LOGOUT_MINUTES = int(_idle_os.environ.get('IDLE_LOGOUT_MINUTES', '20'))
IDLE_WARNING_SECONDS = int(_idle_os.environ.get('IDLE_WARNING_SECONDS', '60'))

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
    'https://*.ngrok.io',
    'https://*.trycloudflare.com',
    'https://*.loca.lt',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
# Add your real production domain(s), comma-separated, e.g.:
#   export DJANGO_CSRF_TRUSTED_ORIGINS="https://app.tawazonoman.com"
CSRF_TRUSTED_ORIGINS += [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Trust ngrok's forwarded HTTPS headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Cookie security.
# Over a plain http://127.0.0.1 connection the browser DROPS any cookie marked
# Secure, which means the CSRF cookie never gets stored and every POST (login,
# OTP request, etc.) fails. So default to relaxed cookies for local dev, and
# only enforce Secure + SameSite=None when serving over HTTPS (e.g. ngrok).
# Turn the strict mode on with:  export COOKIE_SECURE=1
import os as _os
_secure_cookies = _os.environ.get('COOKIE_SECURE', '0') == '1'

CSRF_COOKIE_SECURE      = _secure_cookies
SESSION_COOKIE_SECURE   = _secure_cookies
CSRF_COOKIE_SAMESITE    = 'None' if _secure_cookies else 'Lax'
SESSION_COOKIE_SAMESITE = 'None' if _secure_cookies else 'Lax'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# File storage backends.
#
# Static files (CSS/JS/images bundled with the app) are always served by
# WhiteNoise straight from the app process — no separate config needed.
#
# Uploaded media (case attachments, logos, etc.) stay on local disk by
# default. Set these env vars to instead store them in an S3-compatible
# bucket (Cloudflare R2, AWS S3, DigitalOcean Spaces) — required once running
# on more than one app instance, since local disk isn't shared/durable there:
#   export AWS_STORAGE_BUCKET_NAME="tawazon-media"
#   export AWS_ACCESS_KEY_ID="..."
#   export AWS_SECRET_ACCESS_KEY="..."
#   export AWS_S3_ENDPOINT_URL="https://<account-id>.r2.cloudflarestorage.com"   # R2 only; omit for real AWS S3
#   export AWS_S3_CUSTOM_DOMAIN="media.tawazonoman.com"                          # optional public CDN domain
# ---------------------------------------------------------------------------
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

_media_bucket = os.environ.get('AWS_STORAGE_BUCKET_NAME', '').strip()
if _media_bucket:
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_STORAGE_BUCKET_NAME = _media_bucket
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL') or None
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME') or None
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
else:
    STORAGES['default'] = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

# ---------------------------------------------------------------------------
# Email (used for the client OTP login). Fill these in with your real SMTP
# credentials. They are read from environment variables so you don't have to
# hard-code secrets — e.g. for Gmail:
#   export EMAIL_HOST_USER="you@gmail.com"
#   export EMAIL_HOST_PASSWORD="your-16-char-app-password"
# If no credentials are provided, OTP emails are printed to the runserver
# console instead (handy for local testing without an SMTP server).
# ---------------------------------------------------------------------------
import os

# OTP emails are sent FROM this address (info@tawazonoman.com) to the client's
# registered email. The SMTP login user defaults to the same mailbox.
# Zoho Mail SMTP. If your Zoho account is on a regional data center, change the
# host to match: smtp.zoho.eu / smtp.zoho.in / smtp.zoho.com.au, etc. Business
# (paid) accounts can also use smtppro.zoho.com.
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.zoho.in')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_USE_SSL       = os.environ.get('EMAIL_USE_SSL', '0') == '1'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', 'info@tawazonoman.com')
# SECURITY: no default here — set EMAIL_HOST_PASSWORD in the environment.
# Prefer a Zoho app-specific password over the account password.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Tawazon Collection <info@tawazonoman.com>',
)

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # No SMTP credentials configured — print the email (and OTP) to the console.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# How long an OTP code stays valid, in minutes.
CLIENT_OTP_TTL_MINUTES = int(os.environ.get('CLIENT_OTP_TTL_MINUTES', '10'))

# ---------------------------------------------------------------------------
# Logging.
#
# Without this dict, Django only surfaces WARNING+ from its own loggers, and
# any other logger (e.g. the client-OTP send path) has no handler at all, so
# INFO-level "email sent" confirmations go nowhere — only exceptions would
# reach stderr, via Python's last-resort handler. Route everything to stdout
# so Railway's log stream captures it, at INFO by default (DJANGO_LOG_LEVEL
# to override, e.g. 'DEBUG' while chasing something down).
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.utils.autoreload': {'level': 'WARNING'},
    },
}


# ---------------------------------------------------------------------------
# Error + performance monitoring (Sentry).
#
# Set SENTRY_DSN in the environment to turn it on — get the DSN free at
# sentry.io (create a project, type "Django"). With it enabled you get an
# alert with the exact traceback for any 500, and a "slow transactions" list
# showing which view/query is dragging — so "the dashboard feels slow" turns
# into a specific line to fix instead of a guess. Without SENTRY_DSN set this
# block does nothing.
#   SENTRY_TRACES_SAMPLE_RATE — fraction of requests traced for timing data
#                               (0.1 = 10%). Keep low so it adds no overhead.
# ---------------------------------------------------------------------------
_sentry_dsn = os.environ.get('SENTRY_DSN', '').strip()
if _sentry_dsn:
    import sentry_sdk

    sentry_sdk.init(
        dsn=_sentry_dsn,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
    )


# ---------------------------------------------------------------------------
# Production configuration guard.
#
# Every fallback above is deliberately permissive so local dev "just works":
# no DATABASE_URL means SQLite, no media bucket means the local disk, no SMTP
# password means the console. That is right for a laptop and dangerous on a
# real deploy, where the container filesystem is ephemeral — a missing
# DATABASE_URL would silently accept a week of live data into a SQLite file
# that disappears on the next redeploy, and a missing media bucket would do
# the same to case attachments while leaving the DB rows pointing at them.
# Nothing raises in any of those cases, so there is no traceback to notice.
#
# So when DEBUG is off, refuse to boot instead of failing open. A deploy that
# will not start is a five-minute fix; silent data loss is not recoverable.
# Set DJANGO_ALLOW_UNSAFE_CONFIG=1 to bypass this deliberately (e.g. a staging
# box you genuinely want on SQLite).
# ---------------------------------------------------------------------------
if not DEBUG and os.environ.get('DJANGO_ALLOW_UNSAFE_CONFIG', '') != '1':
    from django.core.exceptions import ImproperlyConfigured

    _problems = []

    if 'sqlite' in DATABASES['default'].get('ENGINE', ''):
        _problems.append(
            "DATABASE_URL is not set, so the app fell back to SQLite on the "
            "container's ephemeral disk. Every write would be lost on the next "
            "redeploy. Attach a managed Postgres instance and set DATABASE_URL."
        )

    if SECRET_KEY == 'django-insecure-CHANGE-ME-for-local-dev-only':
        _problems.append(
            "DJANGO_SECRET_KEY is not set, so the hardcoded dev key is in use. "
            "Sessions and password-reset tokens would be forgeable. Set it to a "
            "long random value."
        )

    if not _media_bucket:
        _problems.append(
            "AWS_STORAGE_BUCKET_NAME is not set, so uploaded case attachments "
            "would be written to the container's ephemeral disk and lost on the "
            "next redeploy, while their DB rows survive pointing at nothing. "
            "Point it at the R2/S3 bucket."
        )

    if not EMAIL_HOST_PASSWORD:
        _problems.append(
            "EMAIL_HOST_PASSWORD is not set, so mail goes to the console "
            "backend. Client-portal OTP emails would never be delivered and no "
            "client could log in — and send_mail() would still report success, "
            "so nothing would appear in Sentry. Set a Zoho app-specific "
            "password."
        )

    if ALLOWED_HOSTS == ['*']:
        _problems.append(
            "DJANGO_ALLOWED_HOSTS is not set, so the app answers to any "
            "hostname, which allows Host-header poisoning. Set it to the real "
            "domains, e.g. 'dashboard.tawazonoman.com'."
        )

    if _problems:
        raise ImproperlyConfigured(
            'Refusing to start with DEBUG=0 and an unsafe configuration:\n\n'
            + '\n\n'.join(f'  * {p}' for p in _problems)
            + '\n\nFix these environment variables, or set '
              'DJANGO_ALLOW_UNSAFE_CONFIG=1 to bypass this check.\n'
        )
